import type {Metadata} from "next";
import {Roboto, Roboto_Mono} from "next/font/google";
import "./globals.css";

// const robotoSans = Roboto({
//     variable: "--font-roboto-sans",
//     subsets: ["latin", "cyrillic"],
// });
//
// const robotoMono = Roboto_Mono({
//     variable: "--font-roboto-mono",
//     subsets: ["latin", "cyrillic"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="ru"
            className={`h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
