[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Valentin", email = "" }
]
requires-python = ">=3.14"
dependencies = [
    "aiomysql>=0.2.0",
    "alembic>=1.19.0",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pymysql>=1.1.0",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
]

[project.scripts]
backend = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""
